spring:
  datasource:
    url: jdbc:postgresql://192.168.78.192:5435/trakyflow_dev
    username: trakyflow_user
    password: devpassword123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: false
    user: trakyflow_user
    password: devpassword123
    outOfOrder: true